version: "3.9"

services:
  backend:
    build: ./backend
    container_name: aibss-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/live_view:/app/live_view
    restart: unless-stopped

  frontend:
    build: ./dog-behavior-dashboard
    container_name: aibss-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
